package(default_visibility = ["//visibility:public"])
load("@onedal//dev/bazel:dal.bzl",
    "dal_module",
    "dal_test_suite",
)

dal_test_suite(
    name = "test",
    auto = True,
    srcs = glob([
        "*.cpp",
    ]),
)
